# Generated by Django 4.2.11 on 2024-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='university_type',
            new_name='ecole_type',
        ),
    ]
