# Generated by Django 4.2.11 on 2024-05-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_rename_university_type_user_ecole_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universite',
            old_name='university_type',
            new_name='universite_type',
        ),
    ]
