# Generated by Django 4.2.11 on 2024-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_rename_university_type_universite_universite_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universite',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='universite',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
