# Generated by Django 4.2.11 on 2024-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_remove_user_name_remove_user_sigle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='sigle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sigle'),
        ),
    ]
