# Generated by Django 4.2.11 on 2024-05-25 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_filiere_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='nbreAnnee',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('sigle', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(max_length=100, null=True)),
                ('entite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
