# Generated by Django 4.2.11 on 2024-05-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0011_filiere_nbreannee_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='entite',
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classe',
            name='option',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='option_sigle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
