# Generated by Django 4.2.11 on 2024-05-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_etudiant_etudiantfiliere_etudiant_filieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(blank=True, max_length=50)),
                ('niveau', models.IntegerField(default=1)),
                ('moy_sem1', models.FloatField(default=0)),
                ('credit_sem1', models.IntegerField(default=0)),
                ('moy_sem2', models.FloatField(default=0)),
                ('credit_sem', models.IntegerField(default=0)),
                ('moy', models.FloatField(default=0)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.filiere')),
            ],
        ),
    ]
