# Generated by Django 4.2.11 on 2024-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0014_cursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantfiliere',
            name='annee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='credit_sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='credit_sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='moy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='moy_sem1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='moy_sem2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Cursus',
        ),
    ]
