# Generated by Django 4.2.11 on 2024-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_etudiantfiliere_annee_etudiantfiliere_credit_sem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='etudiantfiliere',
            name='annee',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='etudiantfiliere',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Attente'), (1, 'Admis'), (2, 'Enjambe'), (3, 'Echoue')], default=0),
        ),
    ]
