# Generated by Django 4.2.11 on 2024-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_remove_etudiant_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
