# Generated by Django 4.2.11 on 2024-05-27 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0020_alter_etudiantfiliere_credit_sem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='credit_sem1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='credit_sem2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='moy_sem1',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='moy_sem2',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
