# Generated by Django 4.2.11 on 2024-05-27 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0022_etudiantfiliere_reinscrit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='moy_sem1',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='etudiantfiliere',
            name='moy_sem2',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
