# Generated by Django 4.2.11 on 2024-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0023_etudiantfiliere_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantfiliere',
            name='classe',
            field=models.BigIntegerField(default=5),
        ),
    ]
