# Generated by Django 4.2.11 on 2024-05-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0024_etudiantfiliere_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiantfiliere',
            old_name='classe',
            new_name='classe_id',
        ),
    ]
